trigger:
  branches:
    include: ['master']
  tags:
    include: ['*']

jobs:
  - job: generate_matrix
    displayName: Generate Matrix
    steps:
      - bash: |
          python ci/matrix.py
        name: generate_matrix

  - job: dist
    displayName: Build Wheel and sdist
    dependsOn:
      - generate_matrix
    pool:
      vmImage: $[ variables.vmImage ]
    strategy:
      maxParallel: 4
      matrix: $[ dependencies.generate_matrix.outputs['generate_matrix.JobsToRun'] ]
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.7
          architecture: x64
      - bash: |
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir dist
        displayName: Build Wheel
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/dist/'
          artifactName: dist

  - job: test
    displayName: Test
    dependsOn:
      - generate_matrix
      - dist
    pool:
      vmImage: $[ variables.vmImage ]
    strategy:
      maxParallel: 4
      matrix: $[ dependencies.generate_matrix.outputs['generate_matrix.JobsToRun'] ]
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(versionSpec)
          architecture: $(architecture)
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'dist'
          downloadPath: $(System.DefaultWorkingDirectory)
      - bash: |
          python -c 'import sys; print(sys.version); print(sys.platform)'
        displayName: Report Python version
      - bash: |
          python -m pip install tox pytest-azurepipelines
        displayName: Install tox
      - bash: |
          python -m tox -e ${TOXENV} --installpkg dist/*.whl
        displayName: tox
          TOXENV: $[ variables.TOXENV ]
      - bash: |
          python -m tox -e codecov
        displayName: codecov
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)

  - job: publish
    displayName: Publish
    dependsOn: test
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.7
          architecture: x64
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'dist'
          downloadPath: $(System.DefaultWorkingDirectory)
      - bash: |
          python -m venv venv
          venv/bin/pip install twine
        displayName: Build venv
      - bash: |
          venv/bin/python ci/twineontag.py
        env:
          TWINE_USERNAME: $(TWINE_USERNAME)
          TWINE_PASSWORD: $(TWINE_PASSWORD)
        displayName: Twine On Tag
